version: "3.8"

services:
  php:
    image: php:8.2-apache
    container_name: php_container
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_DATABASE: act4
      MYSQL_USER: user
      MYSQL_PASSWORD: pas
      MYSQL_ROOT_PASSWORD: pas
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
